### ISSUE TITLE
Add ability to release firefly back

### ISSUE THREAD

**Issue by Fixer-007** [Ezhh/fireflies#4]
Firefly released from bottle will be placed near closest pointed block and will persist if surroundings change. Dissalow placing in liquids (liquids destroy/kill them).

**Comment by Ezhh** [comment]
I'm thinking about the ability to right click on a placed bottle to free them. This would have the advantage of placing them above the bottle, and when the bottle is removed they'd then be up in the air (similar to how they spawn on mapgen) instead of at ground level, which is too low to look right.

**Comment by Ezhh** [comment]
Added ability to release firefly from bottle. (I think this will need protection check as well, so not closing issue yet.)

**Comment by Ezhh** [comment]
Protection check added for when releasing fireflies.
(Still need to look at placement in water)

**Comment by Ezhh** [comment]
@Fixer-007 They now drop as items if placed in water. Please let me know if that seems better. :)

**Comment by Fixer-007** [comment]
Nice. Same for lava? Or do they burn/catch fire in it?

**Comment by Ezhh** [comment]
Seems they remove the lava they are placed in, then any lava from the side will flood in and kill them.
